"""empty message

Revision ID: 0b1ff683301f
Revises: b2351f5cb21d
Create Date: 2019-11-19 17:53:59.446070

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0b1ff683301f'
down_revision = 'a05ed97bab59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('inserted_on', sa.DateTime(), nullable=False),
                    sa.Column('client_id', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(length=125), nullable=False),
                    sa.Column('account_number', sa.String(length=100), nullable=False),
                    sa.Column('routing_number', sa.String(length=100), nullable=False),
                    sa.Column('valid', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('county')
        batch_op.drop_column('crrt')
        batch_op.drop_column('dpbc')
        batch_op.drop_column('fips')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
