"""empty message

Revision ID: 35bcc7c1e637
Revises: 
Create Date: 2019-11-07 23:45:36.560915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35bcc7c1e637'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('reminder_types', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('candidate_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'RECEIVED', 'RUNNING', 'FINISHED', 'ERROR', name='candidateimportstatus'), nullable=False),
    sa.Column('inserted_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=25), nullable=False),
    sa.Column('middle_initial', sa.CHAR(), nullable=True),
    sa.Column('last_name', sa.String(length=25), nullable=False),
    sa.Column('suffix', sa.String(length=25), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip', sa.String(length=5), nullable=False),
    sa.Column('zip4', sa.String(length=4), nullable=False),
    sa.Column('status', sa.Enum('IMPORTED', 'CAMPAIGNED', 'WORKING', 'SUBMITTED', name='candidatestatus'), nullable=True),
    sa.Column('estimated_debt', sa.Integer(), nullable=False),
    sa.Column('prequal_number', sa.String(length=12), nullable=True),
    sa.Column('debt3', sa.Integer(), nullable=False),
    sa.Column('debt15', sa.Integer(), nullable=False),
    sa.Column('debt2', sa.Integer(), nullable=False),
    sa.Column('debt215', sa.Integer(), nullable=False),
    sa.Column('debt3_2', sa.Integer(), nullable=False),
    sa.Column('checkamt', sa.Integer(), nullable=False),
    sa.Column('spellamt', sa.String(length=100), nullable=False),
    sa.Column('debt315', sa.Integer(), nullable=False),
    sa.Column('year_interest', sa.Integer(), nullable=False),
    sa.Column('total_interest', sa.Integer(), nullable=False),
    sa.Column('sav215', sa.Integer(), nullable=False),
    sa.Column('sav15', sa.Integer(), nullable=False),
    sa.Column('sav315', sa.Integer(), nullable=False),
    sa.Column('inserted_on', sa.DateTime(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('county', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=25), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('prequal_number'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=25), nullable=False),
    sa.Column('middle_initial', sa.CHAR(), nullable=True),
    sa.Column('suffix', sa.String(length=25), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip', sa.Integer(), nullable=False),
    sa.Column('zip4', sa.Integer(), nullable=False),
    sa.Column('county', sa.String(length=50), nullable=False),
    sa.Column('crrt', sa.String(length=4), nullable=False),
    sa.Column('dpbc', sa.Integer(), nullable=False),
    sa.Column('fips', sa.Integer(), nullable=False),
    sa.Column('estimated_debt', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('inserted_on', sa.DateTime(), nullable=False),
    sa.Column('language', sa.String(length=25), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('type', sa.Enum('candidate', 'lead', 'client', name='clienttype'), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('sms_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_provider_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('phone_target', sa.String(length=25), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=25), nullable=False),
    sa.Column('last_name', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('require_2fa', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=25), nullable=False),
    sa.Column('personal_phone', sa.String(length=25), nullable=False),
    sa.Column('voip_route_number', sa.String(length=50), nullable=True),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('credit_report_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('customer_token', sa.String(), nullable=True),
    sa.Column('tracking_token', sa.String(length=100), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=True),
    sa.Column('financial_obligation_met', sa.Boolean(), nullable=True),
    sa.Column('password_enc', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('INITIATING_SIGNUP', 'ACCOUNT_CREATED', 'ACCOUNT_VALIDATING', 'ACCOUNT_VALIDATED', 'FULL_MEMBER', name='creditreportsignupstatus'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_token'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('import_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['candidate_imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_tasks_name'), 'import_tasks', ['name'], unique=False)
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reset_key', sa.String(length=128), nullable=True),
    sa.Column('code_hash', sa.String(length=100), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_activated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reset_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_resets')
    op.drop_index(op.f('ix_import_tasks_name'), table_name='import_tasks')
    op.drop_table('import_tasks')
    op.drop_table('credit_report_accounts')
    op.drop_table('users')
    op.drop_table('sms_messages')
    op.drop_table('clients')
    op.drop_table('candidates')
    op.drop_table('candidate_imports')
    op.drop_table('blacklist_tokens')
    op.drop_table('appointments')
    # ### end Alembic commands ###
