"""empty message

Revision ID: 4553b84a0b89
Revises: 4f8d83e11f5e
Create Date: 2019-11-26 18:37:26.288247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4553b84a0b89'
down_revision = '4f8d83e11f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_report_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_client', 'clients', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_report_accounts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_client', type_='foreignkey')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
