"""empty message

Revision ID: 4f8d83e11f5e
Revises: a05ed97bab59
Create Date: 2019-11-26 16:38:47.925703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8d83e11f5e'
down_revision = 'a05ed97bab59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_report_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint('_email_uc', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_report_accounts', schema=None) as batch_op:
        batch_op.drop_constraint('_email_uc', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
