"""empty message

Revision ID: 5946e605a85f
Revises: 35bcc7c1e637
Create Date: 2019-11-08 11:51:47.261643

"""
from alembic import op
import sqlalchemy as sa
from app.main.seed.candidate_dispositions import seed_candidate_disposition_values

# revision identifiers, used by Alembic.
revision = '5946e605a85f'
down_revision = '35bcc7c1e637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    candidate_dispositions = op.create_table('candidate_dispositions',
                                             sa.Column('id', sa.Integer(), nullable=False),
                                             sa.Column('public_id', sa.String(length=100), nullable=False),
                                             sa.Column('inserted_on', sa.DateTime(), nullable=False),
                                             sa.Column('value', sa.String(length=100), nullable=False),
                                             sa.Column('description', sa.String(length=255), nullable=True),
                                             sa.PrimaryKeyConstraint('id'),
                                             sa.UniqueConstraint('public_id')
                                             )

    op.add_column('candidates', sa.Column('disposition_id', sa.Integer(), nullable=True))
    with op.batch_alter_table("candidates") as batch_op:
        batch_op.create_foreign_key('candidates', 'candidate_dispositions', ['disposition_id'], ['id'])

    with op.batch_alter_table('candidate_dispositions', schema=None) as batch_op:
        batch_op.create_unique_constraint('value', ['value'])
    # ### end Alembic commands ###

    op.bulk_insert(candidate_dispositions, seed_candidate_disposition_values())


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidate_dispositions', type_='unique')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'disposition_id')
    op.drop_table('candidate_dispositions')
    # ### end Alembic commands ###
