"""empty message

Revision ID: a7c5f3f21c51
Revises: 5946e605a85f
Create Date: 2019-11-08 12:59:41.954777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c5f3f21c51'
down_revision = '5946e605a85f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_candidates_import_id', 'candidate_imports', ['import_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('import_id')


    # ### end Alembic commands ###
